### ISSUE TITLE
TESTSEGMENT

### ISSUE THREAD

**Issue by Alexufo** [skotz/captcha-breaking-library#6]
TESTSEGMENT always falling

**Comment by skotz** [comment]
Could you please provide the full script that's failing?

**Comment by Alexufo** [comment]
```
SETMODE, ALL
SETUPSEGMENTER,  BLOB, 15, 15, 6
SETUPSOLVER,     MNN, "0123456789", 20, 20
DEFINEPRECONDITIONS
	REMOVENONCOLOR, 60
	MEDIAN, 1
	BINARIZE, 80
	REMOVESMALLBLOBS, 180, 4, 14
ENDPRECONDITIONS

TESTSEGMENT,"I:\qqq\", "I:\qqq\trainers"
```
And this is images 
https://dl.dropboxusercontent.com/u/3013858/qqq.zip

Error
![jmzt640mgkowyh0uflsuug](https://cloud.githubusercontent.com/assets/1562329/12980107/01e225ac-d0ec-11e5-92b5-07e5eb94d67a.png)

**Comment by skotz** [comment]
I think the problem is that TESTSEGMENT takes a single image as the first parameter, not an entire folder (it's for refining your segmentation logic before segmenting an entire folder). If you change the first parameter to a specific image, it should work.
```
SETMODE, ALL
SETUPSEGMENTER,  BLOB, 15, 15, 6
SETUPSOLVER,     MNN, "0123456789", 20, 20
DEFINEPRECONDITIONS
    REMOVENONCOLOR, 60
    MEDIAN, 1
    BINARIZE, 80
    REMOVESMALLBLOBS, 180, 4, 14
ENDPRECONDITIONS

TESTSEGMENT, "qqq\017828.bmp", "segments"
```
With this image:

![017828](https://cloud.githubusercontent.com/assets/11474654/12996554/7747ae16-d0f6-11e5-9d05-eaae98cfe97d.png)

I got these segments:

![000](https://cloud.githubusercontent.com/assets/11474654/12996549/773f690e-d0f6-11e5-889e-7a5130802859.png)
![001](https://cloud.githubusercontent.com/assets/11474654/12996548/773b66ba-d0f6-11e5-8b23-7b10f419fef6.png)
![002](https://cloud.githubusercontent.com/assets/11474654/12996552/77417140-d0f6-11e5-9661-6efe7e39dd8f.png)
![003](https://cloud.githubusercontent.com/assets/11474654/12996551/77411c0e-d0f6-11e5-815a-5cebec9c96e2.png)
![004](https://cloud.githubusercontent.com/assets/11474654/12996553/77417ff0-d0f6-11e5-9943-107641a5d696.png)
![005](https://cloud.githubusercontent.com/assets/11474654/12996550/773fe870-d0f6-11e5-9fd9-aea5915e8002.png)

You can use the TRAIN command to segment an entire folder of images.

**Comment by Alexufo** [comment]
Thanks! This need change in documentation.
