### ISSUE TITLE
Seems TRAIN is not working

### ISSUE THREAD

**Issue by Alexufo** [skotz/captcha-breaking-library#7]
```
SETMODE, ALL
SETUPSEGMENTER,  BLOB, 3, 15, 6
SETUPSOLVER,     MNN, "0123456789", 20, 20
DEFINEPRECONDITIONS
    REMOVENONCOLOR, 60
    MEDIAN, 3
    BINARIZE, 80
    REMOVESMALLBLOBS, 180, 4, 14
ENDPRECONDITIONS
TRAIN, "I:\qqq"
SAVE, I:\qqq\new.db"
```

 new.db  file too small (less then one capthca file 60kb bmp) 
Captcha images very good segmented.
FULLTEST show 0 from 266 images recognized

**Comment by skotz** [comment]
Are you saying you believe the DB file should be larger? The DB file just contains the trained neural network, not the images it was trained on. Does that help?

**Comment by Alexufo** [comment]
Thanks for answer, Scott! good project!

Ok. never mind db size.
This is images
https://dl.dropboxusercontent.com/u/3013858/qqq.zip
And this is script
https://dl.dropboxusercontent.com/u/3013858/test.captcha

After training i do FULLTEST and see 0 from 266 matchs.

**Comment by skotz** [comment]
Ah, you found a bug. Thanks. As it turns out, you can only use LOAD when not in training mode and you can only use FULLTEST when you are in training mode.

So if you use run this command with the script below.

`cbli -s qqq2.captcha -i qqq/075203.bmp`

Your saved solver (14.db) should solve the CAPTCHA. Note that I changed the solver to a BVS for testing, but you can change it back. For this type of CAPTCHA I think the BVS solver works best, though.

```
SETMODE, ALL
SETUPSEGMENTER,  BLOB, 15, 15, 6
SETUPSOLVER,     BVS, "0123456789", 20, 20, Y
LOAD, "14.db"
DEFINEPRECONDITIONS
	REMOVENONCOLOR, 60
	MEDIAN, 1
	BINARIZE, 80
	REMOVESMALLBLOBS, 180, 4, 14
ENDPRECONDITIONS

SOLVE, %image%
```

I'll tag the LOAD/FULLTEST issues as a bug and hopefully get around to fixing it in the not-so-distant future.

As a temporary workaround, you can do the training and FULLTEST in the same run like this:

```
SETMODE, ALL
SETUPSEGMENTER,  BLOB, 15, 15, 6
SETUPSOLVER,     BVS, "0123456789", 20, 20, Y
DEFINEPRECONDITIONS
	REMOVENONCOLOR, 60
	MEDIAN, 1
	BINARIZE, 80
	REMOVESMALLBLOBS, 180, 4, 14
ENDPRECONDITIONS

TRAIN, "qqq"
FULLTEST, "qqq", "test.txt"
```

That gave me some good results:

`TOTAL CORRECT: 213 (213/266 = 80.08%)`

**Comment by vikbeo** [comment]
Hoping this issue can be resolved in next release. Thanks.
